"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class WaypointCommand(object):
    __slots__ = ["op", "name", "tcp_cmd"]

    def __init__(self):
        self.op = ""
        self.name = ""
        self.tcp_cmd = [ 0.0 for dim0 in range(6) ]

    def encode(self):
        buf = BytesIO()
        buf.write(WaypointCommand._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __op_encoded = self.op.encode('utf-8')
        buf.write(struct.pack('>I', len(__op_encoded)+1))
        buf.write(__op_encoded)
        buf.write(b"\0")
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>6d', *self.tcp_cmd[:6]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != WaypointCommand._get_packed_fingerprint():
            raise ValueError("Decode error")
        return WaypointCommand._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = WaypointCommand()
        __op_len = struct.unpack('>I', buf.read(4))[0]
        self.op = buf.read(__op_len)[:-1].decode('utf-8', 'replace')
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.tcp_cmd = struct.unpack('>6d', buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if WaypointCommand in parents: return 0
        tmphash = (0xeb14e5520b8be330) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if WaypointCommand._packed_fingerprint is None:
            WaypointCommand._packed_fingerprint = struct.pack(">Q", WaypointCommand._get_hash_recursive([]))
        return WaypointCommand._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

